---
language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - mvn install:install-file -Dfile=ext/ojdbc6.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0.4 -Dpackaging=jar
notifications:
  email:
    recipients:
        - 1453860636@qq.com
    on_success: change
    on_failure: always
